export default [
  { value: 'Variant' },
  { value: 'Name' },
  { value: 'Images' },
  { value: 'SKU' },
  { value: 'GTIN' },
  { value: 'UPC' },
  { value: 'Ref Id' },
  { value: 'Coming Soon' },
  { value: 'Standard(USD)' },
  { value: 'Wholesale(USD)' },
  { value: 'MSRP(CAD)' },
  { value: 'Europe Standard EUR' },
  { value: 'Euro MSRP' },
  { value: 'AUD' },
  { value: 'Friends & Family' },
  { value: 'Test Price Type' },
  { value: 'USD' },
  { value: 'Special' }
]
